//! macOS pmset wake helper (milestone 2).
//!
//! `pmset schedule wake` needs root, and a sudo token expires in minutes — too short to re-use
//! across schedule changes. So we install a small **root LaunchDaemon** ONCE (one admin prompt):
//! it `WatchPaths` the app's wake-request file and, whenever the app rewrites it, runs
//! `pmset schedule wake "<time>"`. After install the app just writes the request file (no more
//! admin prompts) and the Mac wakes itself ~5 min before the earliest upcoming prime.
//!
//! The app being awake is still required to actually send "hi"; pmset only wakes the Mac so the
//! in-app scheduler (lib.rs) can run. If wake fails, milestone-1's "primed muộn" path still covers it.

use crate::store::Store;
use anyhow::{Context, Result};
use std::path::Path;

/// Label + paths for the privileged helper. The plist lives in the system LaunchDaemons dir; the
/// script + request file live in the app data dir (world-readable; only the request file matters).
pub const HELPER_LABEL: &str = "dev.hoangphan.ai-account-switcher.wake-helper";
const PLIST_PATH: &str = "/Library/LaunchDaemons/dev.hoangphan.ai-account-switcher.wake-helper.plist";

/// Wake the Mac this many minutes before the prime time (brainstorm: T − 5 min).
pub const WAKE_LEAD_MIN: i64 = 5;

/// The shell helper run by the LaunchDaemon as root. Reads the request file (one line:
/// `MM/dd/yy HH:mm:ss`, local time) and schedules a single wake. An empty/missing file clears
/// any wake this helper previously set.
///
/// SECURITY: this script runs as root via the LaunchDaemon. It must live ONLY in a root-owned
/// location (`/usr/local/libexec`), never in a user-writable dir — otherwise any user process
/// could rewrite it and have root execute arbitrary code. It reads the (user-writable) request
/// file but treats its content as data and STRICTLY validates the format before passing it to
/// `pmset`, so a tampered request file can at most schedule a wake, not inject a command.
fn helper_script(request_path: &Path, last_path: &Path) -> String {
    // Paths are placed by the app from non-attacker-controlled values (the app data dir), but we
    // still single-quote them and escape any embedded single quote for defence in depth.
    format!(
        r#"#!/bin/bash
# Auto-generated by AI Account Switcher. Schedules a pmset wake from the app's request file.
set -u
REQ={req}
LAST={last}

# Cancel the wake we previously set (if any), so disabling/rescheduling never leaves a stale wake.
if [ -s "$LAST" ]; then
  OLD="$(/bin/cat "$LAST")"
  if [ -n "$OLD" ]; then
    /usr/bin/pmset schedule cancel wake "$OLD" 2>/dev/null
  fi
  : > "$LAST"
fi

[ -s "$REQ" ] || exit 0
WHEN="$(/bin/cat "$REQ")"
# Strict allow-list: MM/dd/yy HH:MM:SS — refuse anything else (no shell metachars can survive).
if printf '%s' "$WHEN" | /usr/bin/grep -Eq '^[0-1][0-9]/[0-3][0-9]/[0-9][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]$'; then
  /usr/bin/pmset schedule wake "$WHEN" && printf '%s' "$WHEN" > "$LAST"
fi
"#,
        req = sh_single_quote(&request_path.to_string_lossy()),
        last = sh_single_quote(&last_path.to_string_lossy()),
    )
}

/// The LaunchDaemon plist: runs the helper script whenever the request file changes.
fn helper_plist(script_path: &Path, request_path: &Path) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{script}</string>
    </array>
    <key>WatchPaths</key>
    <array>
        <string>{req}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
"#,
        label = xml_escape(HELPER_LABEL),
        script = xml_escape(&script_path.to_string_lossy()),
        req = xml_escape(&request_path.to_string_lossy()),
    )
}

/// Root-owned location the helper script + its bookkeeping live in (NOT user-writable).
const HELPER_SCRIPT_PATH: &str = "/usr/local/libexec/dev.hoangphan.ai-account-switcher-wake-helper.sh";
const HELPER_LAST_PATH: &str = "/usr/local/libexec/dev.hoangphan.ai-account-switcher-wake-last.txt";

/// True if the LaunchDaemon plist is installed.
pub fn helper_installed() -> bool {
    Path::new(PLIST_PATH).exists()
}

/// Install the root LaunchDaemon (one admin prompt). Idempotent: re-running refreshes the script
/// and plist and reloads the daemon. The privileged step installs the script to a root-owned dir
/// and chowns it root:wheel so only root can modify what root executes.
pub fn install_helper(store: &Store) -> Result<()> {
    let request = store.wake_request_path();
    if !request.exists() {
        std::fs::write(&request, "").context("creating wake request file")?;
    }

    // Stage script + plist in the app data dir; the privileged step copies them into root-owned
    // locations and chowns them. The staged copies are transport only — never executed.
    let staged_script = store.root_dir().join("wake-helper.staged.sh");
    let staged_plist = store.root_dir().join("wake-helper.staged.plist");
    std::fs::write(
        &staged_script,
        helper_script(&request, Path::new(HELPER_LAST_PATH)),
    )
    .context("writing wake helper script")?;
    std::fs::write(
        &staged_plist,
        helper_plist(Path::new(HELPER_SCRIPT_PATH), &request),
    )
    .context("writing wake helper plist")?;

    // Build the privileged command from fixed argv pieces + single-quoted paths. The only variable
    // parts are app-controlled filesystem paths, each single-quote-escaped.
    let shell = [
        "/bin/mkdir -p /usr/local/libexec",
        &format!(
            "/bin/cp {} {}",
            sh_single_quote(&staged_script.to_string_lossy()),
            sh_single_quote(HELPER_SCRIPT_PATH)
        ),
        &format!("/usr/sbin/chown root:wheel {}", sh_single_quote(HELPER_SCRIPT_PATH)),
        &format!("/bin/chmod 755 {}", sh_single_quote(HELPER_SCRIPT_PATH)),
        &format!(
            "/bin/cp {} {}",
            sh_single_quote(&staged_plist.to_string_lossy()),
            sh_single_quote(PLIST_PATH)
        ),
        &format!("/usr/sbin/chown root:wheel {}", sh_single_quote(PLIST_PATH)),
        &format!("/bin/chmod 644 {}", sh_single_quote(PLIST_PATH)),
        &format!("/bin/launchctl bootout system {} 2>/dev/null", sh_single_quote(PLIST_PATH)),
        &format!("/bin/launchctl bootstrap system {}", sh_single_quote(PLIST_PATH)),
    ]
    .join("; ");
    let result = run_as_admin(
        &shell,
        "AI Account Switcher cần quyền admin để cài trợ giúp đánh thức máy (pmset)",
    );
    // Clean up the staging files regardless of outcome.
    let _ = std::fs::remove_file(&staged_script);
    let _ = std::fs::remove_file(&staged_plist);
    result
}

/// Single-quote a string for safe embedding in a `/bin/sh` command (wrap in '...' and escape any
/// embedded single quote as '\'').
fn sh_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Minimal XML text escaping for plist string values.
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

/// Remove the LaunchDaemon (one admin prompt) + the root-owned script/bookkeeping, and cancel any
/// wake the helper had pending.
pub fn uninstall_helper() -> Result<()> {
    let shell = [
        // Cancel the wake we set, if any, before removing the bookkeeping file.
        &format!(
            "if [ -s {last} ]; then OLD=\"$(/bin/cat {last})\"; [ -n \"$OLD\" ] && /usr/bin/pmset schedule cancel wake \"$OLD\" 2>/dev/null; fi",
            last = sh_single_quote(HELPER_LAST_PATH)
        ) as &str,
        &format!("/bin/launchctl bootout system {} 2>/dev/null", sh_single_quote(PLIST_PATH)),
        &format!("/bin/rm -f {}", sh_single_quote(PLIST_PATH)),
        &format!("/bin/rm -f {}", sh_single_quote(HELPER_SCRIPT_PATH)),
        &format!("/bin/rm -f {}", sh_single_quote(HELPER_LAST_PATH)),
    ]
    .join("; ");
    run_as_admin(&shell, "AI Account Switcher cần quyền admin để gỡ trợ giúp đánh thức máy")
}

/// Write the desired wake time into the request file (touching it triggers the daemon). `None`
/// clears the wake (writes an empty file). Times are formatted in local time for `pmset`.
pub fn write_wake_request(store: &Store, wake_local: Option<chrono::DateTime<chrono::Local>>) -> Result<()> {
    let content = match wake_local {
        Some(t) => t.format("%m/%d/%y %H:%M:%S").to_string(),
        None => String::new(),
    };
    std::fs::write(store.wake_request_path(), content).context("writing wake request")?;
    Ok(())
}

/// Run a shell command as root via a single Finder admin prompt. Returns an error if the user
/// cancels or the command fails.
fn run_as_admin(shell_command: &str, prompt: &str) -> Result<()> {
    // Escape embedded double-quotes for the AppleScript string.
    let escaped = shell_command.replace('\\', "\\\\").replace('"', "\\\"");
    let script = format!(
        "do shell script \"{escaped}\" with prompt \"{prompt}\" with administrator privileges"
    );
    let output = std::process::Command::new("osascript")
        .arg("-e")
        .arg(&script)
        .output()
        .context("launching osascript for admin prompt")?;
    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        if err.contains("-128") || err.to_lowercase().contains("cancel") {
            anyhow::bail!("Bạn đã hủy cấp quyền admin");
        }
        anyhow::bail!("Không cài được helper: {}", err.trim());
    }
    Ok(())
}
