//! macOS pmset wake helper (milestone 2).
//!
//! `pmset schedule wake` needs root, and a sudo token expires in minutes — too short to re-use
//! across schedule changes. So we install a small **root LaunchDaemon** ONCE (one admin prompt):
//! it `WatchPaths` the app's wake-request file and, whenever the app rewrites it, runs
//! `pmset schedule wake "<time>"`. After install the app just writes the request file (no more
//! admin prompts) and the Mac wakes itself ~5 min before the earliest upcoming prime.
//!
//! The app being awake is still required to actually send "hi"; pmset only wakes the Mac so the
//! in-app scheduler (lib.rs) can run. If wake fails, milestone-1's "primed muộn" path still covers it.

use crate::store::Store;
use anyhow::{Context, Result};
use std::path::Path;

/// Label + paths for the privileged helper. The plist lives in the system LaunchDaemons dir; the
/// script + request file live in the app data dir (world-readable; only the request file matters).
pub const HELPER_LABEL: &str = "dev.hoangphan.ai-account-switcher.wake-helper";
const PLIST_PATH: &str = "/Library/LaunchDaemons/dev.hoangphan.ai-account-switcher.wake-helper.plist";

/// Wake the Mac this many minutes before the prime time (brainstorm: T − 5 min).
pub const WAKE_LEAD_MIN: i64 = 5;

/// The shell helper run by the LaunchDaemon as root. Reads the request file (one line:
/// `MM/dd/yy HH:mm:ss`, local time) and schedules a single wake. An empty/missing file clears
/// any wake this helper previously set.
fn helper_script(request_path: &Path) -> String {
    format!(
        r#"#!/bin/bash
# Auto-generated by AI Account Switcher. Schedules a pmset wake from the app's request file.
REQ="{req}"
if [ ! -s "$REQ" ]; then
  exit 0
fi
WHEN="$(/bin/cat "$REQ")"
if [ -n "$WHEN" ]; then
  /usr/bin/pmset schedule wake "$WHEN"
fi
"#,
        req = request_path.display()
    )
}

/// The LaunchDaemon plist: runs the helper script whenever the request file changes.
fn helper_plist(script_path: &Path, request_path: &Path) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{script}</string>
    </array>
    <key>WatchPaths</key>
    <array>
        <string>{req}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
"#,
        label = HELPER_LABEL,
        script = script_path.display(),
        req = request_path.display()
    )
}

/// Path of the helper script inside the app data dir.
fn script_path(store: &Store) -> std::path::PathBuf {
    store.root_dir().join("wake-helper.sh")
}

/// True if the LaunchDaemon plist is installed.
pub fn helper_installed() -> bool {
    Path::new(PLIST_PATH).exists()
}

/// Install the root LaunchDaemon (one admin prompt). Idempotent: re-running refreshes the script
/// + plist and reloads the daemon.
pub fn install_helper(store: &Store) -> Result<()> {
    let script = script_path(store);
    let request = store.wake_request_path();

    // Write the (unprivileged) helper script + ensure the request file exists.
    std::fs::write(&script, helper_script(&request)).context("writing wake helper script")?;
    if !request.exists() {
        std::fs::write(&request, "").context("creating wake request file")?;
    }

    // Stage the plist in the data dir, then move it into /Library/LaunchDaemons with root via one
    // osascript admin prompt and (re)load it.
    let staged_plist = store.root_dir().join("wake-helper.plist");
    std::fs::write(&staged_plist, helper_plist(&script, &request))
        .context("writing wake helper plist")?;

    let shell = format!(
        "chmod 755 '{script}'; \
         cp '{staged}' '{plist}'; \
         chown root:wheel '{plist}'; \
         chmod 644 '{plist}'; \
         launchctl bootout system '{plist}' 2>/dev/null; \
         launchctl bootstrap system '{plist}'",
        script = script.display(),
        staged = staged_plist.display(),
        plist = PLIST_PATH,
    );
    run_as_admin(&shell, "AI Account Switcher cần quyền admin để cài trợ giúp đánh thức máy (pmset)")
}

/// Remove the LaunchDaemon (one admin prompt).
pub fn uninstall_helper() -> Result<()> {
    let shell = format!(
        "launchctl bootout system '{plist}' 2>/dev/null; rm -f '{plist}'",
        plist = PLIST_PATH
    );
    run_as_admin(&shell, "AI Account Switcher cần quyền admin để gỡ trợ giúp đánh thức máy")
}

/// Write the desired wake time into the request file (touching it triggers the daemon). `None`
/// clears the wake (writes an empty file). Times are formatted in local time for `pmset`.
pub fn write_wake_request(store: &Store, wake_local: Option<chrono::DateTime<chrono::Local>>) -> Result<()> {
    let content = match wake_local {
        Some(t) => t.format("%m/%d/%y %H:%M:%S").to_string(),
        None => String::new(),
    };
    std::fs::write(store.wake_request_path(), content).context("writing wake request")?;
    Ok(())
}

/// Run a shell command as root via a single Finder admin prompt. Returns an error if the user
/// cancels or the command fails.
fn run_as_admin(shell_command: &str, prompt: &str) -> Result<()> {
    // Escape embedded double-quotes for the AppleScript string.
    let escaped = shell_command.replace('\\', "\\\\").replace('"', "\\\"");
    let script = format!(
        "do shell script \"{escaped}\" with prompt \"{prompt}\" with administrator privileges"
    );
    let output = std::process::Command::new("osascript")
        .arg("-e")
        .arg(&script)
        .output()
        .context("launching osascript for admin prompt")?;
    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        if err.contains("-128") || err.to_lowercase().contains("cancel") {
            anyhow::bail!("Bạn đã hủy cấp quyền admin");
        }
        anyhow::bail!("Không cài được helper: {}", err.trim());
    }
    Ok(())
}
